.gitignore
devika.py
src/logger.py
ui/.gitignore

This pull request primarily involves updates to the logging system in the `devika.py` and `src/logger.py` files. The changes include the introduction of a `route_logger` decorator for logging route entry and exit points, and the adjustment of logger instantiation in `devika.py`. A minor change was also made to the `.gitignore` file in the `ui` folder.
* [`devika.py`](diffhunk://#diff-6197fd0ad9004284b414c00f8881514ffa041a569641a338c5d1dec4546f2c51L12-R12): The `Logger` instantiation was moved to the start of the file and all routes were decorated with `@route_logger(logger)`, which logs the entry and exit points of each route. The booting up log message was also moved to the end of the file.
* [`src/logger.py`](diffhunk://#diff-cf7075f01196f97260daf989b9b49230b3812683987ca3dda215408a368275 …

Added logging to all routes

---

devika.py
src/agents/action/action.py
src/agents/agent.py
src/agents/answer/answer.py
src/agents/coder/coder.py
src/agents/decision/decision.py
src/agents/feature/feature.py
src/agents/formatter/formatter.py
src/agents/internal_monologue/internal_monologue.py
src/agents/patcher/patcher.py
src/agents/planner/planner.py
src/agents/reporter/reporter.py
src/agents/researcher/researcher.py
src/agents/runner/runner.py
src/llm/__init__.py
src/llm/llm.py
src/state.py

Hi @mufeedvh , 
Please review and let me know if any change is required as per your understanding of the project.

Token Usage should be inferred from AgentState instead of Lazy initialized global value (TOKEN_USAGE) #10 

---

README.md

Updated README.md to match the environment variable names in the config.toml file.

Update README to match config.toml

---

devika.dockerfile

Noticed debug messages still in the master branch, removed them. 😄

fix(dockerfile): remove debug messages

---

ui/src/lib/components/TerminalWidget.svelte

Forgetting Import for xterm-addon-fit library

Adding import to xterm-addon-fit

---

src/llm/llm.py

Changes :
-> Added support for all the Groq models available( as of 27-Mar-2024)
-> Renamed variables to accommodate the changes
**Tested Thoroughly**, works smoothly as expected!
Thank you !

Feature - Added support for other Groq models

---

ui/src/lib/api.js

Issues:
-> Even though token usage was getting recorded in Db smoothly after recent code changes, it wasn't showing up properly in UI and also in logs
Fixed this issue:
Now, token usage is reflected properly in UI and logs. **Tested thoroughly**, works smoothly as expected!
Thank you!

Fixed - token usage in UI & logs

---

README.md

Created documentation for the following
1. web_search methods and accepted values
2. google search api
documenting pr #99

Created documentation for changing web_search methods and google search api

---

devika.py
src/agents/agent.py
src/agents/coder/coder.py
src/agents/feature/feature.py
src/browser/browser.py
src/browser/search.py
src/llm/llm.py
src/socket_instance.py
src/state.py
ui/src/lib/components/BrowserWidget.svelte

Fixing playwright using sync API

---

src/agents/patcher/patcher.py

If code encounters an error, then patcher gives a key error which makes Devika never solve the error.

Update patcher.py for Key Error while patching code with error

---

README.md

Fix README.md confusing message

---

devika.py
ui/src/lib/components/BrowserWidget.svelte
ui/src/lib/components/MessageInput.svelte
ui/src/lib/components/TerminalWidget.svelte
ui/src/routes/+page.svelte
ui/src/routes/settings/+page.svelte

solved https://github.com/stitionai/devika/issues/344

Fix: setting page loading issue, messages from user

---

src/agents/agent.py

Fixed these issues:
1. The browser variable was not defined
2. The async function in its replacement was not used

Pdf download in agent.py

---

README.md
sample.config.toml
src/config.py
src/llm/openai_client.py

Added support for custom Open AI API endpoint.
#191

Feature: Custom OpenAI API Endpoints

---

.github/pull_request_template.md
devika.py
src/agents/agent.py
src/browser/search.py
src/logger.py

- remove API keys from logs
- fix none links issue
- 
Fixes https://github.com/stitionai/devika/issues/430, https://github.com/stitionai/devika/issues/411

Fix: none link and remove api from log

---

README.md

Changed minimum requried python versio nto 3.10
for e.g.
solved #455

python min version - 3.10

---

src/llm/llm.py

for e.g.
* [550 ] Selecting llama3:latest and llama3:70b in the UI always results in only llama3:latest (8B)
For llama model , It don't need split(':'), ollama needs whole name for model id
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.
Fixes #

Fix: bug 550 : make sure the model_name with the ollama list

---

devika.dockerfile
devika.py

This fixes a CORS issue that happens when running locally with `docker compose`, and a YAML file missing error. I also moved a Dockerfile install step to improve caching. 
Explain what existing problem does the pull request solve?
1. Fix a CORS issue
2. Fix a yaml file not found issue
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.
1. `docker compose up --build`, and wait
2. Visit `http://localhost:3000/` and see that the web UI now works.

fix: CORS issue and yaml issue

---

src/llm/llm.py

Enable Gemini 1.5 models in config. these are better in code generation for pygame.
Explain what existing problem does the pull request solve?
Adds new model config for gemini 1.5
I tested with conway's game of life example 
Fixes #

add latest gemini 1.5 config

---

src/llm/llm.py

Add: gpt-4o-mini
